FROM debian:12.0-slim

ENV SCRIPTS_DIR /scripts
ENV BACKUP_DIR /backup
ENV CONFIG_DIR /config
ENV PARENT_FOLDER_ID XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ENV GOOGLE_CRED_FILENAME google-key.json

COPY . /

RUN bash $SCRIPTS_DIR/setup_image.sh